#!/bin/bash

# The play command from the sox package will play any file format supported by sox 
#   using the default audio device, e.g

# `dnf provides /usr/share/sounds/freedesktop/stereo/bell.oga`
## sound-theme-freedesktop (@System)

SOUND="${1:-bell}"
SOUND_PATH="/usr/share/sounds/freedesktop/stereo"
if [ ! -f ${SOUND_PATH}/${SOUND}.oga ]; then  # make sure we have a good fallback
  SOUND="bell"
fi

if [ ! -f ${SOUND_PATH}/${SOUND}.oga ]; then  # make sure we have a good fallback
  # `dnf provides /usr/share/sounds/alsa/Front_Center.wav `
  ## alsa-utils (@System)
  play -q /usr/share/sounds/alsa/Front_Center.wav  # Should always exist...
  exit 0
fi

play -q ${SOUND_PATH}/${SOUND}.oga

# https://unix.stackexchange.com/questions/632670/the-paradox-of-logical-and-and-or-in-a-bash-script-to-check-the-succes
exit 0
